In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
path = r"C:\Users\jvill\OneDrive - UC San Diego\Vallon Kidney\10-14-26 BR_Images_HSI data\Round2-arithmetic\all_images_roi_metrics.parquet"
df = pd.read_parquet(path)

In [4]:
df

,Sample ID,Image Name,ROI Inst,ROI #,Region Idx,Label,mask_name,Area (px),Protein_Turnover Mean,Protein_Turnover Std,...,% Centroid_3 (TAG Mix),% Centroid_4 (Kidney Background),Dominant Centroid,% Dominant Centroid,Centroid_X,Centroid_Y,Vertices_JSON,Pixel_Size_um,Image_Path,UID
0,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,1,1,ROI1,PT-S1/S2,PT-S1/S2,17943,0.1298,0.0760,...,23.59,10.42,Centroid_1 (Cholesterol (ovine)),48.73,81.367413,773.127359,"[[-0.7239425778388977, 832.0377197265625], [15...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,9f775c5f-abb8-47d8-811d-6bc32c551ab8
1,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,2,2,ROI1,PT-S1/S2,PT-S1/S2,8800,0.1249,0.0679,...,22.49,12.20,Centroid_1 (Cholesterol (ovine)),45.68,193.676581,826.209318,"[[138.74514770507812, 836.7313842773438], [150...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,1cdfad7e-80a6-4f9f-b150-ce71194d5d0e
2,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,3,3,ROI1,PT-S1/S2,PT-S1/S2,10557,0.1374,0.0758,...,25.00,11.20,Centroid_1 (Cholesterol (ovine)),47.47,218.073356,719.647503,"[[161.54298400878906, 748.22216796875], [176.9...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,64114cc0-0aba-49b2-8af4-144c93feb741
3,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,4,4,ROI1,PT-S1/S2,PT-S1/S2,14502,0.1262,0.0769,...,18.11,7.95,Centroid_1 (Cholesterol (ovine)),54.72,520.376740,661.466618,"[[465.29058837890625, 624.1751098632812], [454...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,5b8a3e38-b0d6-4fad-909b-24d4907ad161
4,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,5,5,ROI1,PT-S1/S2,PT-S1/S2,15418,0.1379,0.0930,...,19.73,9.87,Centroid_1 (Cholesterol (ovine)),48.84,679.005016,740.114918,"[[609.453369140625, 744.8695678710938], [613.4...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,25b69da0-7d16-44f2-96fe-ecee6bd75f54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1374,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,479,1,12,mTAL,mTAL,35240,0.0757,0.0489,...,4.23,39.84,Centroid_2 (Kidney Background),43.53,317.118298,599.934288,"[[224.5811309814453, 567.59716796875], [237.63...",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,6bf49aa5-19ed-430f-be15-4ff7a349bf61
1375,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,480,2,12,mTAL,mTAL,8059,0.0798,0.0519,...,5.20,42.18,Centroid_2 (Kidney Background),42.25,328.370243,849.230453,"[[271.300537109375, 835.6002807617188], [298.1...",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,cc285e91-50aa-4b1b-a539-ce94fa7d9ba2
1376,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,481,3,12,mTAL,mTAL,6149,0.0744,0.0514,...,2.60,44.84,Centroid_4 (Kidney Background),44.84,440.455622,784.462377,"[[398.0658264160156, 780.5263061523438], [401....",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,63e56625-8795-416c-8ca2-1126e3efa104
1377,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,482,4,12,mTAL,mTAL,10325,0.0705,0.0481,...,2.80,33.33,Centroid_2 (Kidney Background),51.93,846.907663,955.735796,"[[781.5906372070312, 949.9257202148438], [786....",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,c5794e65-7550-4ded-9073-1986512b7179
1378,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,483,5,12,mTAL,mTAL,3219,0.0639,0.0447,...,3.82,40.82,Centroid_2 (Kidney Background),40.85,981.506647,858.763271,"[[964.5652465820312, 819.9817504882812], [958....",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,5fa23800-aadf-4a9c-bd09-c7a01e29f179

In [5]:
df_condition = df.copy()
df_condition['Sample ID'] = df_condition['Sample ID'].astype(int)

In [6]:
conditions = [df_condition["Sample ID"] <= 4, (df_condition["Sample ID"] > 4) & (df_condition["Sample ID"] <= 8), (df_condition["Sample ID"] > 8) & (df_condition["Sample ID"] <= 12), (df_condition["Sample ID"] > 12) & (df_condition["Sample ID"] <= 16), (df_condition["Sample ID"] > 16) & (df_condition["Sample ID"] <= 20), (df_condition["Sample ID"] > 20) & (df_condition["Sample ID"] <= 24), (df_condition["Sample ID"] > 24) & (df_condition["Sample ID"] <= 28), (df_condition["Sample ID"] > 28) & (df_condition["Sample ID"] <= 32)]

In [7]:
choices = ['Ctrl/Veh', 'Ctrl/SGLT2i', 'WD/Veh', 'WD/SGLT2i','Ctrl/Veh', 'Ctrl/SGLT2i', 'WD/Veh', 'WD/SGLT2i']
df_condition["Condition"] = np.select(conditions, choices, default="Unknown")

In [8]:
df_condition.to_parquet(r"C:\Users\jvill\OneDrive - UC San Diego\Vallon Kidney\10-14-26 BR_Images_HSI data\Round2-arithmetic\all_images_roi_metrics-final.parquet", index=False)

In [9]:
df_condition

,Sample ID,Image Name,ROI Inst,ROI #,Region Idx,Label,mask_name,Area (px),Protein_Turnover Mean,Protein_Turnover Std,...,% Centroid_4 (Kidney Background),Dominant Centroid,% Dominant Centroid,Centroid_X,Centroid_Y,Vertices_JSON,Pixel_Size_um,Image_Path,UID,Condition
0,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,1,1,ROI1,PT-S1/S2,PT-S1/S2,17943,0.1298,0.0760,...,10.42,Centroid_1 (Cholesterol (ovine)),48.73,81.367413,773.127359,"[[-0.7239425778388977, 832.0377197265625], [15...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,9f775c5f-abb8-47d8-811d-6bc32c551ab8,Ctrl/Veh
1,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,2,2,ROI1,PT-S1/S2,PT-S1/S2,8800,0.1249,0.0679,...,12.20,Centroid_1 (Cholesterol (ovine)),45.68,193.676581,826.209318,"[[138.74514770507812, 836.7313842773438], [150...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,1cdfad7e-80a6-4f9f-b150-ce71194d5d0e,Ctrl/Veh
2,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,3,3,ROI1,PT-S1/S2,PT-S1/S2,10557,0.1374,0.0758,...,11.20,Centroid_1 (Cholesterol (ovine)),47.47,218.073356,719.647503,"[[161.54298400878906, 748.22216796875], [176.9...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,64114cc0-0aba-49b2-8af4-144c93feb741,Ctrl/Veh
3,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,4,4,ROI1,PT-S1/S2,PT-S1/S2,14502,0.1262,0.0769,...,7.95,Centroid_1 (Cholesterol (ovine)),54.72,520.376740,661.466618,"[[465.29058837890625, 624.1751098632812], [454...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,5b8a3e38-b0d6-4fad-909b-24d4907ad161,Ctrl/Veh
4,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,5,5,ROI1,PT-S1/S2,PT-S1/S2,15418,0.1379,0.0930,...,9.87,Centroid_1 (Cholesterol (ovine)),48.84,679.005016,740.114918,"[[609.453369140625, 744.8695678710938], [613.4...",0.331456,C:/Users/jvill/OneDrive - UC San Diego/Vallon ...,25b69da0-7d16-44f2-96fe-ecee6bd75f54,Ctrl/Veh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1374,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,479,1,12,mTAL,mTAL,35240,0.0757,0.0489,...,39.84,Centroid_2 (Kidney Background),43.53,317.118298,599.934288,"[[224.5811309814453, 567.59716796875], [237.63...",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,6bf49aa5-19ed-430f-be15-4ff7a349bf61,Ctrl/Veh
1375,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,480,2,12,mTAL,mTAL,8059,0.0798,0.0519,...,42.18,Centroid_2 (Kidney Background),42.25,328.370243,849.230453,"[[271.300537109375, 835.6002807617188], [298.1...",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,cc285e91-50aa-4b1b-a539-ce94fa7d9ba2,Ctrl/Veh
1376,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,481,3,12,mTAL,mTAL,6149,0.0744,0.0514,...,44.84,Centroid_4 (Kidney Background),44.84,440.455622,784.462377,"[[398.0658264160156, 780.5263061523438], [401....",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,63e56625-8795-416c-8ca2-1126e3efa104,Ctrl/Veh
1377,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,482,4,12,mTAL,mTAL,10325,0.0705,0.0481,...,33.33,Centroid_2 (Kidney Background),51.93,846.907663,955.735796,"[[781.5906372070312, 949.9257202148438], [786....",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,c5794e65-7550-4ded-9073-1986512b7179,Ctrl/Veh
1378,17,17-hSRS-ROI12-781.3-806.5nm-10us-scale40k-offs...,483,5,12,mTAL,mTAL,3219,0.0639,0.0447,...,40.82,Centroid_2 (Kidney Background),40.85,981.506647,858.763271,"[[964.5652465820312, 819.9817504882812], [958....",0.331456,C:/Users/sidda/Downloads/JORGE_KIDNEY/data_rem...,5fa23800-aadf-4a9c-bd09-c7a01e29f179,Ctrl/Veh