In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
path = r"C:\Users\jvill\OneDrive - UC San Diego\Vallon Kidney\headless_arithmetic_outputs\all_images_roi_metrics.parquet"
df = pd.read_parquet(path)

,Sample ID,Image Name,ROI Inst,ROI #,Region Idx,Label,mask_name,Area (px),Top Match,% Top Match,...,LD_Lipid_to_Protein Mean,LD_Lipid_to_Protein Std,LD_Lipid_to_Protein Median,LD_Lipid_to_Protein Min,LD_Lipid_to_Protein Max,LD_Lipid_Unsaturation Mean,LD_Lipid_Unsaturation Std,LD_Lipid_Unsaturation Median,LD_Lipid_Unsaturation Min,LD_Lipid_Unsaturation Max
0,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,1,1,ROI1,PT-S1/S2,PT-S1/S2,20142,Sterols,37.9,...,0.5115,0.0367,0.5156,0.4355,0.5653,0.1173,0.0496,0.1191,0.0425,0.2043
1,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,2,2,ROI1,PT-S1/S2,PT-S1/S2,9865,Sterols,36.1,...,0.5975,0.0281,0.5935,0.5493,0.6536,0.0751,0.0402,0.0713,0.0019,0.2027
2,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,3,3,ROI1,PT-S1/S2,PT-S1/S2,11576,Sterols,35.7,...,0.6090,0.0311,0.6221,0.5550,0.6471,0.0892,0.0468,0.0821,0.0254,0.1579
3,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,4,4,ROI1,PT-S1/S2,PT-S1/S2,15805,Sterols,40.7,...,0.5285,0.0276,0.5318,0.4500,0.5820,0.0880,0.0386,0.0857,0.0061,0.2121
4,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,5,5,ROI1,PT-S1/S2,PT-S1/S2,16908,Sterols,38.3,...,0.5466,0.0465,0.5552,0.3805,0.6672,0.1039,0.0445,0.1028,0.0110,0.2056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,186,1,Top6,PT-S3,PT-S3,59117,Background,77.9,...,0.5593,0.0671,0.5596,0.3607,0.7190,0.0683,0.0365,0.0649,0.0002,0.1908
1675,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,187,2,Top6,PT-S3,PT-S3,47730,Background,77.2,...,0.5661,0.0435,0.5656,0.4139,0.6908,0.0644,0.0340,0.0627,0.0000,0.1653
1676,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,188,3,Top6,PT-S3,PT-S3,20636,Background,81.2,...,0.5587,0.0442,0.5600,0.4248,0.6713,0.0548,0.0353,0.0474,0.0022,0.1599
1677,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,189,4,Top6,PT-S3,PT-S3,45673,Background,77.5,...,0.5663,0.0458,0.5638,0.4248,0.6966,0.0691,0.0363,0.0678,0.0005,0.1805
1678,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,190,5,Top6,PT-S3,PT-S3,9325,Background,83.0,...,0.5814,0.0325,0.5831,0.5058,0.6764,0.0516,0.0218,0.0502,0.0016,0.1218

In [11]:
df_condition = df.copy()
df_condition['Sample ID'] = df_condition['Sample ID'].astype(int)

In [13]:
conditions = [df_condition["Sample ID"] <= 4, (df_condition["Sample ID"] > 4) & (df_condition["Sample ID"] <= 8), (df_condition["Sample ID"] > 8) & (df_condition["Sample ID"] <= 12), (df_condition["Sample ID"] > 12) & (df_condition["Sample ID"] <= 16), (df_condition["Sample ID"] > 16) & (df_condition["Sample ID"] <= 20), (df_condition["Sample ID"] > 20) & (df_condition["Sample ID"] <= 24), (df_condition["Sample ID"] > 24) & (df_condition["Sample ID"] <= 28), (df_condition["Sample ID"] > 28) & (df_condition["Sample ID"] <= 32)]

In [16]:
choices = ['Ctrl/Veh', 'Ctrl/SGLT2i', 'WD/Veh', 'WD/SGLT2i','Ctrl/Veh', 'Ctrl/SGLT2i', 'WD/Veh', 'WD/SGLT2i']
df_condition["Condition"] = np.select(conditions, choices, default="Unknown")

In [18]:
df_condition

,Sample ID,Image Name,ROI Inst,ROI #,Region Idx,Label,mask_name,Area (px),Top Match,% Top Match,...,LD_Lipid_to_Protein Std,LD_Lipid_to_Protein Median,LD_Lipid_to_Protein Min,LD_Lipid_to_Protein Max,LD_Lipid_Unsaturation Mean,LD_Lipid_Unsaturation Std,LD_Lipid_Unsaturation Median,LD_Lipid_Unsaturation Min,LD_Lipid_Unsaturation Max,Condition
0,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,1,1,ROI1,PT-S1/S2,PT-S1/S2,20142,Sterols,37.9,...,0.0367,0.5156,0.4355,0.5653,0.1173,0.0496,0.1191,0.0425,0.2043,Ctrl/Veh
1,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,2,2,ROI1,PT-S1/S2,PT-S1/S2,9865,Sterols,36.1,...,0.0281,0.5935,0.5493,0.6536,0.0751,0.0402,0.0713,0.0019,0.2027,Ctrl/Veh
2,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,3,3,ROI1,PT-S1/S2,PT-S1/S2,11576,Sterols,35.7,...,0.0311,0.6221,0.5550,0.6471,0.0892,0.0468,0.0821,0.0254,0.1579,Ctrl/Veh
3,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,4,4,ROI1,PT-S1/S2,PT-S1/S2,15805,Sterols,40.7,...,0.0276,0.5318,0.4500,0.5820,0.0880,0.0386,0.0857,0.0061,0.2121,Ctrl/Veh
4,18,18-hSRS-ROI1-781.3-806.5nm-250mw-500V-10us-zoo...,5,5,ROI1,PT-S1/S2,PT-S1/S2,16908,Sterols,38.3,...,0.0465,0.5552,0.3805,0.6672,0.1039,0.0445,0.1028,0.0110,0.2056,Ctrl/Veh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,186,1,Top6,PT-S3,PT-S3,59117,Background,77.9,...,0.0671,0.5596,0.3607,0.7190,0.0683,0.0365,0.0649,0.0002,0.1908,Ctrl/SGLT2i
1675,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,187,2,Top6,PT-S3,PT-S3,47730,Background,77.2,...,0.0435,0.5656,0.4139,0.6908,0.0644,0.0340,0.0627,0.0000,0.1653,Ctrl/SGLT2i
1676,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,188,3,Top6,PT-S3,PT-S3,20636,Background,81.2,...,0.0442,0.5600,0.4248,0.6713,0.0548,0.0353,0.0474,0.0022,0.1599,Ctrl/SGLT2i
1677,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,189,4,Top6,PT-S3,PT-S3,45673,Background,77.5,...,0.0458,0.5638,0.4248,0.6966,0.0691,0.0363,0.0678,0.0005,0.1805,Ctrl/SGLT2i
1678,8,8-hSRS-ROI6-781.3-806.5nm-250mw-500V-20us-zoom...,190,5,Top6,PT-S3,PT-S3,9325,Background,83.0,...,0.0325,0.5831,0.5058,0.6764,0.0516,0.0218,0.0502,0.0016,0.1218,Ctrl/SGLT2i

In [19]:
df_condition.to_parquet(r"C:\Users\jvill\OneDrive - UC San Diego\Vallon Kidney\headless_arithmetic_outputs\all_images_roi_metrics-final.parquet", index=False)